### PR TITLE
solve issue 60, 'connection_created' signal called too early when cre…

### PR DESCRIPTION
**Pull request by robinechuca**
All the details are written in [`issue`](https://github.com/klauer/qtpynodeeditor/issues/60).

### CODE REVIEW

**Review by klauer — APPROVED** [review]
Thanks so much, @robinechuca! Looks like the PR wasn't so tough for you after all. 👍 

The tests pass and some quick local testing on my end indicates this works well.

**Comment by robinechuca** [comment]
Thank you for your quick response and action! The last PR I submitted was discussed for nearly a month before being validated.
Thank you, it's thanks to behavior like yours that people are motivated to contribute to free software. Thank you very much ;)

**Comment by robinechuca** [comment]
Hello, it's been a while since the repository has been updated on PyPi.
Would it be possible to publish a version 0.3.1?

**Comment by klauer** [comment]
Thanks for the nudge, @robinechuca. I'll publish an update later today or tomorrow.

**Pull request merged**
